# SPDX-License-Identifier: MIT

ARG CHRONO_DIR
ARG PACKAGE_DIR
ARG USERSHELLPROFILE

# Update CMake options
ENV CMAKE_OPTIONS="${CMAKE_OPTIONS} \
    -DCHRONO_CUDA_ARCHITECTURES=${CHRONO_CUDA_ARCHITECTURE} \
    -DCH_ENABLE_MODULE_FSI=ON"
